name: Feature request 🚀
description: Suggest a new idea !
labels: ['status: needs triage']
body:
  - type: markdown
    attributes:
      value: |
        ### ⚠️ Before you continue

        This issues are looking for contributor : https://github.com/users/ph-ausseil/projects/1/views/2?layout=table&filterQuery=status%3A%22Looking+for+a+volunteer%22 

        * **Thoroughly search the [existing issues] before creating a new one**
        [existing issues]: https://github.com/ph-ausseil/AFAAS/issues?q=is%3Aissue


  - type: markdown
    attributes:
      value: |
        ⚠️ Please do not prefix your Title with "Bug" , "Fix" , our CI does it ⚠️

        Provide a meanful title that leaves to no ambiguity

  - type: textarea
    attributes:
      label: Summary 💡
      description: Describe how it should work.
  - type: textarea
    attributes:
      label: Examples 🌈
      description: Provide a link to other implementations, or screenshots of the expected behavior.
  - type: textarea
    attributes:
      label: Motivation 🔦
      description: What are you trying to accomplish? How has the lack of this feature affected you? Providing context helps us come up with a solution that is more useful in the real world.
